name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-test-ci:latest
    - name: POST build action
      run: docker images
    - name: RUN docker
      run: $ docker run -it --rm -d -p 8080:80 --name web my-test-ci:latest

      
